const Router = require('express')
const router = new Router()
const watchLaterMoviesController = require('../controllers/watchLaterMoviesController')
const userController = require('../controllers/userController')
const authMiddleware = require('../middleware/authMiddleware')
const watchedMoviesController = require('../controllers/watchedMoviesController')
const checkRole = require('../middleware/checkRoleMiddleware')

router.post('/registration', userController.registration)
router.post('/login', userController.login)
router.post('/watchlater', watchLaterMoviesController.create)
router.get('/watchlater', watchLaterMoviesController.getAll)
router.delete('/watchlater/:id', watchLaterMoviesController.delete)
router.post('/watched', watchedMoviesController.create)
router.put('/rating/:id', watchedMoviesController.changeRating)
router.get('/watched', watchedMoviesController.getAll)
router.delete('/watched/:id', watchedMoviesController.delete)
router.get('/auth', authMiddleware, userController.check )

module.exports = router